name = "GeoIP"
uuid = "abcde121-99a1-4d4f-92c5-2a3c6888d26a"
authors = ["Andrey Oskin", "Seth Bromberger", "contributors: https://github.com/JuliaWeb/GeoIP.jl/graphs/contributors"]
version = "0.6.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
IPNets = "66763231-799b-5fff-8662-389acfc33a85"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
CSV = "0.8"
Geodesy = "1"
IPNets = "1"
ZipFile = "0.7, 0.8, 0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
